version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Online-Marketplace
    networks:
      - Online-Marketplace

  test-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Online-Marketplace
    networks:
      - Online-Marketplace
networks:
  Online-Marketplace:
    driver: bridge
